(module jabber "swindle.ss"
  (require* "auth.ss")
  (require* "client.ss")
  (require* "dom.ss")
  (require* "error.ss")
  (require* "exn.ss")
  (require* "iq.ss")
  (require* "jid.ss")
  (require* "logging.ss")
  (require* "message.ss")
  (require* "presence.ss")
  (require* "read.ss")
  (require* "stanza.ss")
  (require* "stream.ss")
)
